@host = http://localhost:8082

### Agregar un nuevo buffet
POST {{host}}/api/buffet
Content-Type: application/json

{
    "code": "B001",
    "name": "Delicias del mar",
    "price": 25.99,
    "foodType": "marino",
    "measureUnit": "plato",
    "picture": "url_to_picture.jpg"
}

### Obtener todos los buffets
GET {{host}}/api/buffet

### Obtener un buffet por código
GET {{host}}/api/buffet/B001

### Actualizar un buffet por código
PUT {{host}}/api/buffet/B001
Content-Type: application/json

{
    "name": "Vegetales del huerto",
    "price": 20.99,
    "foodType": "vegetal",
    "measureUnit": "plato",
    "picture": "url_to_new_picture.jpg"
}

### Eliminar un buffet por código
DELETE {{host}}/api/buffet/B001
