@host = http://localhost:8082
@profesorId = 65c7c9ff797651af9e850c1c

### Crear un nuevo profesor
POST {{host}}/api/profesores 
Content-Type: application/json

{
  "identificacion": "12345678",
  "nombrecompleto": "Juan Pérez",
  "correoElectronico": "juan.perez@example.com",
  "edad": 40,
  "direccion": "Calle Falsa 123"
}

### Obtener todos los profesores
GET {{host}}/api/profesores 

### Obtener un profesor por ID
GET {{host}}/api/profesores/{{profesorId}}  

### Actualizar un profesor por ID
PUT {{host}}/api/profesores/{{profesorId}} 
Content-Type: application/json

{
  "identificacion": "87654321",
  "nombrecompleto": "Juan Pérez Actualizado",
  "correoElectronico": "juan.perez.actualizado@example.com",
  "edad": 41,
  "direccion": "Calle Verdadera 321"
}

### Eliminar un profesor por ID
DELETE {{host}}/api/profesores/{{profesorId}}
